### ISSUE TITLE
Possibility to associate scripts with toggles

### ISSUE THREAD

**Issue by acama** [KarsMulder/evsieve#15]
I would like to be able to use ddcutil with my current KVM setup. I know that currently evsieve can allow associating a command to a hook. But as it stands now, this requires using two different keys as described in the "Toggle events between two virtual devices - Advanced Variations" section. It would be nice if we could map a shell command to a toggle target. This way one can use a single key combination to both switch between inputs.

**Comment by KarsMulder** [comment]
Do you have a proposed syntax for this feature?

I considered adding something for this in the past, but the main reason a feature for this wasn't added is because the stake of keeping the documentation/interface sufficiently simple weighted harder than the little usefulness this feature would provide.

**Comment by acama** [comment]
```
        --input  /dev/input/by-id/usb-Keychron_K8_Keychron_K8-event-kbd persist=reopen domain=kb grab \
        --input  /dev/input/by-id/usb-SteelSeries_SteelSeries_Aerox_3_Wireless-event-mouse    persist=reopen domain=ms grab \
        --hook   key:leftalt@host-kb key:rightalt@host-kb toggle   exec-shell="echo HOST >> /tmp/switchy"\
        --hook   key:leftalt@guest-kb key:rightalt@guest-kb toggle  exec-shell="echo GUEST >> /tmp/switchy" \
        --map    key:leftalt key:rightalt @host-kb \
        --toggle @kb @guest-kb @host-kb  \
        --toggle @ms @guest-ms @host-ms  \
        --output @host-kb create-link=/dev/input/by-id/host-kbd   \
        --output @host-ms create-link=/dev/input/by-id/host-mouse      \
        --output @guest-kb create-link=/dev/input/by-id/guest-kbd \
        --output @guest-ms create-link=/dev/input/by-id/guest-mouse
```
Essentially this is what I am trying to achieve, I use left alt + right alt to switch between my guest KVM and host. But I want to execute a 'ddcutil' command when I am coming from the guest, and another one when I am coming from the host. It doesn't seem like the syntax I have here is correct ?

If this is already possible as it stands now, it seems like my feature request can be ignored.

**Comment by KarsMulder** [comment]
Move the `--hook` after the `--toggle` arguments. Move the `--map` after the `--hook`. Replace `echo HOST >> /tmp/switchy` with whatever ddcutil command you want.

```
        --input  /dev/input/by-id/usb-Keychron_K8_Keychron_K8-event-kbd persist=reopen domain=kb grab \
        --input  /dev/input/by-id/usb-SteelSeries_SteelSeries_Aerox_3_Wireless-event-mouse    persist=reopen domain=ms grab \
        --toggle @kb @guest-kb @host-kb  \
        --toggle @ms @guest-ms @host-ms  \
        --hook   key:leftalt@host-kb key:rightalt@host-kb toggle   exec-shell="echo HOST >> /tmp/switchy"\
        --hook   key:leftalt@guest-kb key:rightalt@guest-kb toggle  exec-shell="echo GUEST >> /tmp/switchy" \
        --map    key:leftalt  @host-kb \
        --map    key:rightalt @host-kb \
        --output @host-kb create-link=/dev/input/by-id/host-kbd   \
        --output @host-ms create-link=/dev/input/by-id/host-mouse      \
        --output @guest-kb create-link=/dev/input/by-id/guest-kbd \
        --output @guest-ms create-link=/dev/input/by-id/guest-mouse
```

Finally, note that `--map key:leftalt key:rightalt @host-kb` maps a single event (left alt) to two events (right alt + left alt @ host-kb), which is probably something different from what you intended it to do. If you want to keep both the left and right alt keys always on the host keyboard, you need to use two maps.

**Comment by acama** [comment]
Thanks for your help :) Seems like at least he feature I was looking for already exists.
