### ISSUE TITLE
compilation issues on 32 bits boards (+ patch)

### ISSUE THREAD

**Issue by nadenislamarre** [KarsMulder/evsieve#31]
this patch could interest you :
https://github.com/batocera-linux/batocera.linux/pull/8709

the error was:
error[E0308]: mismatched types
  --> src/time.rs:66:18
   |
66 |             sec: timespec.tv_sec,
   |                  ^^^^^^^^^^^^^^^ expected `i64`, found `i32`

error[E0308]: mismatched types
  --> src/time.rs:67:19
   |
67 |             nsec: timespec.tv_nsec,
   |                   ^^^^^^^^^^^^^^^^ expected `i64`, found `i32`

error[E0308]: mismatched types
  --> src/time.rs:75:18
   |
75 |             sec: timeval.tv_sec,
   |                  ^^^^^^^^^^^^^^ expected `i64`, found `i32`

error[E0308]: mismatched types
  --> src/time.rs:76:49
   |
76 |             nsec: NANOSECONDS_PER_MICROSECOND * timeval.tv_usec,
   |                                                 ^^^^^^^^^^^^^^^ expected `i64`, found `i32`

error[E0277]: cannot multiply `i64` by `i32`
  --> src/time.rs:76:47
   |
76 |             nsec: NANOSECONDS_PER_MICROSECOND * timeval.tv_usec,
   |                                               ^ no implementation for `i64 * i32`

**Comment by KarsMulder** [comment]
This patch has been implemented. Thank you for the report.
