### ISSUE TITLE
Key repeat request to kernel

### ISSUE THREAD

**Issue by mikethebos** [KarsMulder/evsieve#36]
I would like to know how the `repeat=enable` feature is implemented ([https://github.com/gvalkov/python-evdev/issues/192](https://github.com/gvalkov/python-evdev/issues/192)).

I see a reference to `EVIOCGREP` in your libevdev binding, but that is a read syscall.  

(I hope to implement this feature in my own application soon using python-evdev.  Thanks!  If you want my code to be licensed in a specific manner due to this inspiration, let me know.)

**Comment by KarsMulder** [comment]
The kernel will automatically generate repeat event when the the capabilities for the [EV_REP](https://www.kernel.org/doc/html/latest/input/event-codes.html#ev-rep)-type events are enabled on the virtual output device. In C terms, it would require the following libevdev calls:

```
libevdev_enable_event_type(dev, EV_REP);
libevdev_enable_event_code(dev, EV_REP, REP_DELAY, &250);
libevdev_enable_event_code(dev, EV_REP, REP_PERIOD, &33);
```

Based on my personal tests:
* The kernel just ignores whatever value for delay/period you pass to it; the kernel will always use a delay of 250 and a period of 33 regardless of what value you pass to it;
* The repeat events you write to the output device will show up no matter whether you enable EV_REP or not. This means that you can write repeat events to a device that is not capable of EV_REP, and conversely, if you _do_ write repeat events to an EV_REP capable device, the device will have double the usual amount of repeat events (the ones you wrote + the autogenerated ones.)

**Comment by mikethebos** [comment]
Thanks for your help!
