### ISSUE TITLE
Update libc crate version from 0.2.82 to 0.2.125 or higher

### ISSUE THREAD

**Issue by k0tran** [KarsMulder/evsieve#51]
Hello, I noticed that in Cargo.toml:25 you specificatlly set libc version to 0.2.82. Can you update the crate, please?

The reason behind this is that support for loongarch64 cpu arch appeared in libc 0.2.125 (https://github.com/rust-lang/libc/releases/tag/0.2.125). Right now to port evsieve I'm vendoring libc crate and then patching it to partially bring the crate up to that version.

I also tried to run `cargo test` with libc versions 0.2.125 and * (0.2.169) and all tests passed. Both on my x86_64 and loongarch64 machines

**Comment by KarsMulder** [comment]
Thank you for bringing this to my attention. I have updated libc to the current latest version, 0.2.169. (Commit 0471b917f9f681066522ff97bc8427bfd5e7f083)
